name: site-deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Deploy site
    runs-on: ubuntu-latest
    environment: netlify
    container: golang:latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Make goba.ga
      run: go run main.go
    - name: deploy goba.ga
      uses: jsmrcaga/action-netlify-deploy@master
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_KEY }}
        NETLIFY_SITE_ID: ${{ secrets.DEV_API }}
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: template
